Warehouse/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Warehouse.DataAccessLayer.Models;
using Warehouse.DataAccessLayer.Data;
using Warehouse.ClassLibrary;

namespace Warehouse.Controllers
{
    public class PaymentsController : Controller
    {
        ApplicationDbContext _context;
        public PaymentsController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: Payments
        public ActionResult Index()
        {
            return View();
        }

        // GET: Payments
        public ActionResult UserOrders()
        {
            //var items = new OrderItem[]{
            //    new OrderItem{ Id = 1, Price = new Price(100), Product = _context.Products.Include(p => p.Pictures).Include(p => p.Unit)
            //        .Include(p => p.ManufactureCountry).FirstOrDefault(i=>i.Id == 1)},
            //    new OrderItem{ Id = 2, Price = new Price(102), Product = _context.Products.Include(p => p.Pictures).Include(p => p.Unit)
            //        .Include(p => p.ManufactureCountry).FirstOrDefault(i=>i.Id == 2)},

            //};
            //var resultPrice = new Price(items.Sum(i => i.Price.Penny));


            //var l = new List<Order>();
            //l.Add(new Order { OrderDate = DateTime.Now, Id = 2, UserId = "123", OrderStatus = _context.OrderStatuses.Find(1), TotalPrice = resultPrice, Items = items.ToList() });

            //items = new OrderItem[]{
            //    new OrderItem{ Id = 3, Price = new Price(399999), Product = _context.Products.Include(p => p.Pictures).Include(p => p.Unit)
            //        .Include(p => p.ManufactureCountry).FirstOrDefault(i=>i.Id == 5)},
            //    new OrderItem{ Id = 4, Price = new Price(26099), Product = _context.Products.Include(p => p.Pictures).Include(p => p.Unit)
            //        .Include(p => p.ManufactureCountry).FirstOrDefault(i=>i.Id == 3)},

            //};
            //resultPrice = new Price(items.Sum(i => i.Price.Penny));

            //l.Add(new Order { OrderDate = DateTime.Today, Id = 1, UserId = "123", OrderStatus = _context.OrderStatuses.Find(3), TotalPrice = resultPrice, Items = items.ToList() });
            return View(null);
        }

        // GET: Payments/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Payments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Payments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Payments/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Payments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Payments/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Payments/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Warehouse/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Warehouse.BusinessLogicLayer.Interfaces;
using Warehouse.BusinessLogicLayer.DataTransferObjects;
using AutoMapper;
using Warehouse.ViewModels;
using Warehouse.BusinessLogicLayer.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Warehouse.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        private readonly IMapper _mapper;
        private readonly IUnitService _unitService;
        private readonly ICountriesService _countriesService;

        public ProductsController(IProductService productService, IUnitService unitService, IMapper mapper, ICountriesService countriesService)
        {
            _productService = productService;
            _mapper = mapper;
            _unitService = unitService;
            _countriesService = countriesService;
        }

        public ActionResult Index(ProductFilterParams f)
        {
            if (f.MinCount == null) f.MinCount = 1;
            var products = _mapper.Map<IEnumerable<ProductViewModel>>(_productService.ReadMany(f));
            var viewModel = _mapper.Map<ProductFilterViewModel>(f);
            viewModel.Products = products;
            return View(viewModel);
        }

        public async Task<ActionResult> Details(int id)
        {
            try
            {
                ProductViewModel p = _mapper.Map<ProductViewModel>(await _productService.ReadAsync(id));
                if (p == null) Response.StatusCode = 404;
                return View(p);
            }
            catch
            {
                return NotFound();
            }
        }

        public ActionResult Create()
        {
            ViewBag.Units = new SelectList(_unitService.ReadAll(), "Id", "UnitString");
            ViewBag.Countries = new SelectList(_countriesService.ReadAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductViewModel p, IFormCollection collection)
        {
            try
            {
                p.Pictures = collection["pictures"].Select(s => new UrlViewModel { UrlString = s }).ToList();
                var id = await _productService.CreateAsync(_mapper.Map<ProductDTO>(p));
                return RedirectToAction(nameof(Details), new { Id = id });
            }
            catch
            {
                return Create();
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            var defSelect = new SelectListItem { Value = "-1", Text = "Не выбрано", Selected = true };
            ViewBag.Units = (new SelectList(_unitService.ReadAll(), "Id", "UnitString")).Append(defSelect);
            ViewBag.Countries = (new SelectList(_countriesService.ReadAll(), "Id", "Name")).Append(defSelect);
            return View(_mapper.Map<ProductViewModel>(await _productService.ReadAsync(id)));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProductViewModel p, IFormCollection collection)
        {
            try
            {
                p.Pictures = collection["pictures"].Select(s => new UrlViewModel { UrlString = s }).ToList();
                await _productService.UpdateAsync(_mapper.Map<ProductDTO>(p));

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var product = await _productService.ReadAsync(id);
                if (product == null) return NotFound();
                await _productService.DeleteAsync(product);

                return Ok();
            }
            catch
            {
                return BadRequest();
            }
        }
    }
}

Warehouse/Views/Payments/Create.cshtml
@using Warehouse.ViewModels
@model int
@{
    Layout = "_Layout";
    ViewData["Title"] = "Заказать у поставщиков";
}

<section class="order-form my-4 mx-4 col-lg-9">
    <div class="container pt-4">

        <div class="row">
            <div class="col-12">
                <h3>Заказать у поставщика</h3>
                <hr class="mt-1">
            </div>
            <div class="col-12">

                <div class="row mt-7 mx-4">
                    <div class="col-12 col-sm-8">
                        <label class="order-form-label">Поставщик</label>
                        <input class="order-form-input" placeholder="" required>
                    </div>
                </div>

                <div class="row mt-7 mx-4">
                    <div class="col-12 col-sm-8">
                        <label class="order-form-label">Товар</label>
                        <input class="order-form-input" placeholder="" required>
                    </div>
                    <div class="col-12 col-sm-3">
                        <label class="order-form-label">Количество</label>
                        <input class="order-form-input" type="number" min="1" placeholder="" required>
                    </div>
                </div>

                <div class="row mt-7 mx-4">
                    <div class="col-12 col-sm-8">
                        <div class="col-sm-3">
                            <button type="button" class="btn btn-primary d-block mx-auto btn-submit"><i class="fas fa-plus"></i></button>
                        </div>
                    </div>
                </div>

                <div class="row mt-3 mx-4">
                    <label class="order-form-label">Адрес доставки</label>
                    <input class="order-form-input" value="Минск, улица ленина, д. 7" placeholder="" required>
                </div>
                <div class="row mt-3 justify-content-center">
                    <div class="col-auto">
                        <button type="button" id="btnSubmit" class="btn btn-primary d-block mx-auto btn-submit">Обработать</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

Warehouse/Views/Payments/Details.cshtml
@using Warehouse.ViewModels
@model int
@{
    Layout = "_Layout";
    ViewData["Title"] = "Заказать у поставщиков";
}

<section class="order-form my-4 mx-4 col-lg-9">
    <div class="container pt-4">

        <div class="row">
            <div class="col-12">
                <h3>Оплатить заказ у поставщика</h3>
                <hr class="mt-1">
            </div>
            <div class="col-12">

                <div class="row mt-7 mx-4">
                    <div class="col-12 col-sm-8">
                        <label class="order-form-label">Поставщик</label>
                        <input class="order-form-input" value="ООО 'Пример' " placeholder="" readonly>
                    </div>
                </div>

                <div class="row mt-7 mx-4">
                    <div class="col-12 col-sm-8">
                        <label class="order-form-label">Реквизиты</label>
                        <textarea class="order-form-input" placeholder="" readonly>ИНН: 6449013711, КПП: 644901001О, КПО: 24399828, ОГРН: 1026402000657</textarea>
                    </div>
                </div>

                <div class="row mt-7 mx-4">
                    <div class="col-12 col-sm-8">
                        <label class="order-form-label">Товар</label>
                        <input class="order-form-input" value="Материнская плата ASRock X370 Pro4" placeholder="" readonly>
                    </div>
                    <div class="col-12 col-sm-3">
                        <label class="order-form-label">Количество</label>
                        <input class="order-form-input" value="100" type="number" min="1" placeholder="" readonly>
                    </div>
                </div>

                <div class="row mt-7 mx-4">
                    <div class="col-12 col-sm-8">
                        <label class="order-form-label">Товар</label>
                        <input class="order-form-input" value="Процессор AMD Ryzen 7 2700" placeholder="" readonly>
                    </div>
                    <div class="col-12 col-sm-3">
                        <label class="order-form-label">Количество</label>
                        <input class="order-form-input" value="100" type="number" min="1" placeholder="" readonly>
                    </div>
                </div>

                <div class="row mt-2 mx-4">
                    <div class="col-12 col-sm-8">
                        <b>Итоговая стоимость: 1245432.9 руб.</b>
                    </div>
                </div>

                <div class="row mt-2 mx-4">
                    <div class="col-12 col-sm-8">
                        <p class="text-danger"><b>Статус: неоплачено</b></p>
                    </div>
                </div>

                <div class="row mt-3 mx-4">
                    <label class="order-form-label">Адрес доставки</label>
                    <input class="order-form-input" value="Минск, улица ленина, д. 7" placeholder="" readonly>
                </div>
                <div class="row mt-3 justify-content-center">
                    <div class="col-auto">
                        <button type="button" id="btnSubmit" class="btn btn-primary d-block mx-auto btn-submit">Оплачено</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

Warehouse/Views/Payments/Index.cshtml
@using Warehouse.ViewModels
@model OrderViewModel
@{
    ViewData["Title"] = "Необработанные заказы";
    Layout = "_Layout";
}

<h2>Неоплаченные заказы у поставщиков:</h2>
<ul class="list-group">
    <li class="list-group-item"><a asp-controller="Payments" asp-action="Details" asp-route-id="1">Заказ №1. Материнская плата ASRock X370 Pro4, ...</a></li>
    <li class="list-group-item"><a asp-controller="Payments" asp-action="Details" asp-route-id="1">Заказ №2. Процессор AMD Ryzen 7 2700, ...</a></li>
</ul>

Warehouse/Views/Payments/UserOrders.cshtml
@using Warehouse.ViewModels;
@model IEnumerable<OrderViewModel>
@{
    ViewData["Title"] = "Мои заказы";
    Layout = "_Layout";
}

@if (User.Identity.Name == "")
{
    <h1>Неоплаченные заказы</h1>
}
else
{
    <h1>Неоплаченные заказы</h1>
}


@foreach (var o in Model)
{
    <div class="card margin-bottom-15px">
        <a asp-action="Details" asp-route-id="@o.Id" class="card-title" style="margin-left:30px;">Заказ №@o.Id <small class="text-muted">@o.OrderDate.ToString("HH:mm dd MMMM yyyy")</small></a>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-8">
                    @foreach (var orderItem in o.Items)
                    {
                        <div class="card card-secondary lg-12">
                            <div class="row no-gutters">
                                <div class="col-lg-2">
                                    <img src="@orderItem.Product.Pictures.FirstOrDefault()" class="card-img" alt="...">
                                </div>
                                <div class="col-lg-8">
                                    <div class="card-body">
                                        <h6 class="card-title"><a asp-controller="Products" asp-action="Details" asp-route-id="@orderItem.Product.Id">@orderItem.Product.Name</a></h6>
                                        <p class="card-text" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">@orderItem.Product.Description</p>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <h6><b>@orderItem.Price</b></h6>
                                </div>
                            </div>
                        </div>

                    }
                </div>
                <div class="col-auto">
                    <p>Итоговая стоимость: <b>@o.TotalPrice</b></p>
                    <div class="card">
                        <div class="text-center">
                            <div class="card-title">Состояние заказа:</div>
                            <p class="card-text">@o.OrderStatuses.First()</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}