Warehouse/Controllers/CartController.cs
using System.Collections.Generic;
using System.Linq;
using Warehouse.BusinessLogicLayer.Exceptions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Warehouse.BusinessLogicLayer.Interfaces;
using Warehouse.BusinessLogicLayer.DataTransferObjects;
using Warehouse.ViewModels;
using AutoMapper;
using System.Security.Claims;
using Warehouse.BusinessLogicLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Warehouse.BusinessLogicLayer.Extensions;

namespace Warehouse.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly IMapper _mapper;
        public CartController(ICartService cartService, IMapper mapper)
        {
            _mapper = mapper;
            _cartService = cartService;
        }

        // GET: Cart
        public async Task<ActionResult> Index()
        {
            try
            {
                return View(_mapper.Map<CartViewModel>(await _cartService.GetCartAsync(User)));
            }
            catch
            {
                return Unauthorized();
            }
        }

        // GET: Cart/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Cart/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cart/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cart/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cart/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<ActionResult> Add(int Productid)
        {
            try
            {
                await _cartService.AddCartProductAsync(new CartProductDTO { ProductId = Productid }, User);
                return Ok();
            }
            catch (UnauthorizeAccessException)
            {
                return StatusCode(403);
            }
            catch
            {
                return BadRequest();
            }
        }

        // POST: Cart/Delete/5
        [HttpDelete]
        public async Task<ActionResult> Delete(int cartProductid)
        {
            try
            {
                await _cartService.DeleteCartProductAsync(cartProductid, User);
                return Ok();
            }
            catch (UnauthorizeAccessException)
            {
                return Forbid();
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            catch
            {
                return BadRequest();
            }
        }
    }
}

Warehouse/Controllers/CourierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Warehouse.BusinessLogicLayer.Extensions;
using Warehouse.BusinessLogicLayer.Interfaces;
using Warehouse.BusinessLogicLayer.Models;
using Warehouse.ViewModels;

namespace Warehouse.Controllers
{
    public class CourierController : Controller
    {
        private readonly IOrderService _service;
        private readonly IMapper _mapper;
        public CourierController(IOrderService service, IMapper mapper)
        {
            _service = service;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View(_mapper.Map<IEnumerable<OrderViewModel>>(_service.ReadMany(User, new OrderFilterParams { UserId = "1" })));
        }

        public IActionResult Deliver()
        {
            return View(_mapper.Map<IEnumerable<OrderViewModel>>(_service.ReadMany(User, new OrderFilterParams { LastShippedForUserId = User.GetUserId(), OrderStatusString = "Передан курьеру" })));
        }
    }
}

Warehouse/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Warehouse.DataAccessLayer.Models;
using Warehouse.DataAccessLayer.Data;
using AutoMapper;
using Warehouse.ViewModels;
using Warehouse.BusinessLogicLayer.DataTransferObjects;
using Warehouse.ClassLibrary;
using Warehouse.BusinessLogicLayer.Interfaces;
using Warehouse.BusinessLogicLayer.Models;
using Warehouse.BusinessLogicLayer.Exceptions;
using Microsoft.AspNetCore.Mvc.Rendering;
using Warehouse.BusinessLogicLayer.Extensions;

namespace Warehouse.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IOrderService _orderService;
        private readonly IProductService _productService;
        private readonly IOrderStatusesService _orderStatusesService;
        private readonly IApplicationUserService _userService;
        public OrdersController(IOrderService orderService, IProductService productService,
            IOrderStatusesService orderStatusesService, IMapper mapper, IApplicationUserService userService)
        {
            _mapper = mapper;
            _orderService = orderService;
            _productService = productService;
            _orderStatusesService = orderStatusesService;
            _userService = userService;
        }

        [Authorize]
        public ActionResult Index()
        {
            return View(_mapper.Map<IEnumerable<OrderViewModel>>(_orderService.ReadMany(User)));
        }

        public async Task<ActionResult> Unpaid()
        {
            return View(_mapper.Map<IEnumerable<OrderViewModel>>(
                _orderService.ReadMany(User, new OrderFilterParams { OrderStatusString = "Ожидание оплаты" })));
        }

        public IActionResult All()
        {
            return View(_mapper.Map<IEnumerable<OrderViewModel>>(
                _orderService.ReadMany(User, new OrderFilterParams {})));
        }

        public async Task<ActionResult> Details(int id)
        {
            var users = _mapper.Map<IEnumerable<ApplicationUserViewModel>>(_userService.ReadMany(new ApplicationUserFilterParams { UserNameContains = "courier" }));
            ViewBag.Couriers = new SelectList(users, "Id", "UserName");
            return View(_mapper.Map<OrderViewModel>(await _orderService.ReadAsync(User, id)));
        }

        public ActionResult Create([FromQuery] int[] ids)
        {
            IEnumerable<ProductViewModel> products = _mapper.Map<IEnumerable<ProductViewModel>>(_productService.ReadMany(new ProductFilterParams { Ids = ids }));
            return View(products);
        }

        [HttpPost]
        public async Task<ActionResult> Create(IFormCollection collection)
        {
            IEnumerable<ProductDTO> products = null; 
            try
            {
                var ids = collection["ids[]"];
                products = _productService.ReadMany(new ProductFilterParams { Ids = ids.Select(int.Parse) });
                await _orderService.Create(User, products);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                try
                {
                    return View(_mapper.Map<ProductViewModel>(products));
                }
                catch
                {
                    return View(null);
                }
            }
        }

        public ActionResult Edit(int id)
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<ActionResult> SetPayed(int id)
        {
            try
            {
                await _orderStatusesService.SetPayed(id, User);
                return RedirectToAction(nameof(Details), new { id });
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            catch (UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch
            {
                return BadRequest();
            }
        }

        public ActionResult Delete(int id)
        {
            return View();
        }

        public ActionResult Deliver(int id)
        {
            return View(_mapper.Map<IEnumerable<OrderViewModel>>(
                _orderService.ReadMany(User, new OrderFilterParams { OrderStatusString = "Ожидание доставки"})));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Warehouse/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Warehouse.BusinessLogicLayer.Interfaces;
using Warehouse.BusinessLogicLayer.DataTransferObjects;
using AutoMapper;
using Warehouse.ViewModels;
using Warehouse.BusinessLogicLayer.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Warehouse.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        private readonly IMapper _mapper;
        private readonly IUnitService _unitService;
        private readonly ICountriesService _countriesService;

        public ProductsController(IProductService productService, IUnitService unitService, IMapper mapper, ICountriesService countriesService)
        {
            _productService = productService;
            _mapper = mapper;
            _unitService = unitService;
            _countriesService = countriesService;
        }

        public ActionResult Index(ProductFilterParams f)
        {
            if (f.MinCount == null) f.MinCount = 1;
            var products = _mapper.Map<IEnumerable<ProductViewModel>>(_productService.ReadMany(f));
            var viewModel = _mapper.Map<ProductFilterViewModel>(f);
            viewModel.Products = products;
            return View(viewModel);
        }

        public async Task<ActionResult> Details(int id)
        {
            try
            {
                ProductViewModel p = _mapper.Map<ProductViewModel>(await _productService.ReadAsync(id));
                if (p == null) Response.StatusCode = 404;
                return View(p);
            }
            catch
            {
                return NotFound();
            }
        }

        public ActionResult Create()
        {
            ViewBag.Units = new SelectList(_unitService.ReadAll(), "Id", "UnitString");
            ViewBag.Countries = new SelectList(_countriesService.ReadAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductViewModel p, IFormCollection collection)
        {
            try
            {
                p.Pictures = collection["pictures"].Select(s => new UrlViewModel { UrlString = s }).ToList();
                var id = await _productService.CreateAsync(_mapper.Map<ProductDTO>(p));
                return RedirectToAction(nameof(Details), new { Id = id });
            }
            catch
            {
                return Create();
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            var defSelect = new SelectListItem { Value = "-1", Text = "Не выбрано", Selected = true };
            ViewBag.Units = (new SelectList(_unitService.ReadAll(), "Id", "UnitString")).Append(defSelect);
            ViewBag.Countries = (new SelectList(_countriesService.ReadAll(), "Id", "Name")).Append(defSelect);
            return View(_mapper.Map<ProductViewModel>(await _productService.ReadAsync(id)));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProductViewModel p, IFormCollection collection)
        {
            try
            {
                p.Pictures = collection["pictures"].Select(s => new UrlViewModel { UrlString = s }).ToList();
                await _productService.UpdateAsync(_mapper.Map<ProductDTO>(p));

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var product = await _productService.ReadAsync(id);
                if (product == null) return NotFound();
                await _productService.DeleteAsync(product);

                return Ok();
            }
            catch
            {
                return BadRequest();
            }
        }
    }
}

Warehouse/Pages/Shared/_Layout.cshtml
@inject SignInManager<Warehouse.DataAccessLayer.Models.ApplicationUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Warehouse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button id="sidebarCollapse" class="btn mr-2">
                    <i class="fa fa-bars" aria-hidden="true"></i>
                </button>
                <a class="navbar-brand" asp-area="" asp-page="/Index">Warehouse</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>*@

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Products" asp-action="Index">Каталог</a>
                        </li>
                        @if (User.Identity.Name != "User1@gmail.com" && SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark">@DateTime.Now.ToString("dd MMMM yyyy"), 3124215 руб.</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="wrapper">
        <!-- Sidebar -->
        <nav id="sidebar" class="col-md-1">
            @await Html.PartialAsync("_SidebarPartial.cshtml")
        </nav>
        <div class="container">
            <main role="main" class="pb-3 ">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Warehouse - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    @RenderSection("Scripts", required: false)
    @await Html.PartialAsync("_ValidationScriptsPartial")
</body>
</html>

Warehouse/Pages/Shared/_SideBarPartial.cshtml
@if (User.Identity.IsAuthenticated)
{
    <ul class="list-unstyled components">
        <li><a asp-controller="Orders" asp-action="Index">Мои заказы</a></li>
        <li><a asp-controller="Cart" asp-action="Index">Моя корзина</a></li>
        <li><a asp-controller="ClientRequests" asp-action="Index">Мои запросы</a></li>
    </ul>


    @if (User.Identity.Name == "StoreKeeper1@gmail.com"
      || User.Identity.Name == "Adm1n@gmail.com")
    {
        <p>Кладовщик</p>
        <ul class="list-unstyled components">
            <li><a asp-controller="Products" asp-action="Create">Оформить</a></li>
            <li><a asp-controller="Orders" asp-action="Deliver">Ожидают доставку</a></li>
        </ul>
    }

    @if (User.Identity.Name == "Courier1@gmail.com"
      || User.Identity.Name == "Adm1n@gmail.com")
    {
        <p>Курьер</p>
        <ul class="list-unstyled components">
            <li><a asp-controller="Courier" asp-action="Deliver">Я доставляю</a></li>
            <li><a asp-controller="Orders" asp-action="Deliver">Ожидают доставку</a></li>
        </ul>
    }

    @if (User.Identity.Name == "UsersManager1@gmail.com"
      || User.Identity.Name == "Adm1n@gmail.com")
    {
        <p>Менеджер по клиентам</p>
        <ul class="list-unstyled components">
            <li><a asp-controller="ClientRequests" asp-action="Filter">Запросы</a></li>
        </ul>
    }

    @if (User.Identity.Name == "PurchasingManager1@gmail.com"
      || User.Identity.Name == "Adm1n@gmail.com")
    {
        <p>Менеджер по закупкам</p>
        <ul class="list-unstyled components">
            <li><a asp-controller="Supplier" asp-action="Index">Поставщики</a></li>
            <li><a asp-controller="SupplierOrders" asp-action="Create">Заказать у поставщика</a></li>
            <li><a asp-controller="SupplierOrders" asp-action="Index">Заказы у поставщиков</a></li>
        </ul>
    }

    @if (User.Identity.Name == "Accountant1@gmail.com"
      || User.Identity.Name == "Adm1n@gmail.com")
    {
        <p>Бухгалтер</p>
        <ul class="list-unstyled components">
            <li><a asp-controller="Orders" asp-action="Unpaid">Не оплаченные заказы</a></li>
            <li><a asp-controller="SupplierOrders" asp-action="Unpaid">Не оплаченные заказы у поставщиков</a></li>
        </ul>
    }
}

Warehouse/Pages/Shared/_StatusBar.cshtml
<p>@DateTime.Now.ToString("dd MMMM yyyy"), 3124215 руб.</p>