Warehouse/ViewModels/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Warehouse.ClassLibrary;

namespace Warehouse.ViewModels
{
    public class OrderViewModel
    {
        public int Id { get; set; }
        public DateTime OrderDate { get; set; }
        public string UserId { get; set; }
        public ApplicationUserViewModel User { get; set; }
        public List<OrderItemViewModel> Items { get; set; }
        public Price TotalPrice { get; set; }
        public List<OrderOrderStatusViewModel> OrderStatuses { get; set; }
        public List<ShipmentViewModel> Shipments { get; set; }
    }
}

Warehouse/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Warehouse.DataAccessLayer.Models;
using Warehouse.DataAccessLayer.Data;
using AutoMapper;
using Warehouse.ViewModels;
using Warehouse.BusinessLogicLayer.DataTransferObjects;
using Warehouse.ClassLibrary;
using Warehouse.BusinessLogicLayer.Interfaces;
using Warehouse.BusinessLogicLayer.Models;
using Warehouse.BusinessLogicLayer.Exceptions;
using Microsoft.AspNetCore.Mvc.Rendering;
using Warehouse.BusinessLogicLayer.Extensions;

namespace Warehouse.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IOrderService _orderService;
        private readonly IProductService _productService;
        private readonly IOrderStatusesService _orderStatusesService;
        private readonly IApplicationUserService _userService;
        public OrdersController(IOrderService orderService, IProductService productService,
            IOrderStatusesService orderStatusesService, IMapper mapper, IApplicationUserService userService)
        {
            _mapper = mapper;
            _orderService = orderService;
            _productService = productService;
            _orderStatusesService = orderStatusesService;
            _userService = userService;
        }

        [Authorize]
        public ActionResult Index()
        {
            return View(_mapper.Map<IEnumerable<OrderViewModel>>(_orderService.ReadMany(User)));
        }

        public async Task<ActionResult> Unpaid()
        {
            return View(_mapper.Map<IEnumerable<OrderViewModel>>(
                _orderService.ReadMany(User, new OrderFilterParams { OrderStatusString = "Ожидание оплаты" })));
        }

        public IActionResult All()
        {
            return View(_mapper.Map<IEnumerable<OrderViewModel>>(
                _orderService.ReadMany(User, new OrderFilterParams {})));
        }

        public async Task<ActionResult> Details(int id)
        {
            var users = _mapper.Map<IEnumerable<ApplicationUserViewModel>>(_userService.ReadMany(new ApplicationUserFilterParams { UserNameContains = "courier" }));
            ViewBag.Couriers = new SelectList(users, "Id", "UserName");
            return View(_mapper.Map<OrderViewModel>(await _orderService.ReadAsync(User, id)));
        }

        public ActionResult Create([FromQuery] int[] ids)
        {
            IEnumerable<ProductViewModel> products = _mapper.Map<IEnumerable<ProductViewModel>>(_productService.ReadMany(new ProductFilterParams { Ids = ids }));
            return View(products);
        }

        [HttpPost]
        public async Task<ActionResult> Create(IFormCollection collection)
        {
            IEnumerable<ProductDTO> products = null; 
            try
            {
                var ids = collection["ids[]"];
                products = _productService.ReadMany(new ProductFilterParams { Ids = ids.Select(int.Parse) });
                await _orderService.Create(User, products);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                try
                {
                    return View(_mapper.Map<ProductViewModel>(products));
                }
                catch
                {
                    return View(null);
                }
            }
        }

        public ActionResult Edit(int id)
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<ActionResult> SetPayed(int id)
        {
            try
            {
                await _orderStatusesService.SetPayed(id, User);
                return RedirectToAction(nameof(Details), new { id });
            }
            catch (NotFoundException)
            {
                return NotFound();
            }
            catch (UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch
            {
                return BadRequest();
            }
        }

        public ActionResult Delete(int id)
        {
            return View();
        }

        public ActionResult Deliver(int id)
        {
            return View(_mapper.Map<IEnumerable<OrderViewModel>>(
                _orderService.ReadMany(User, new OrderFilterParams { OrderStatusString = "Ожидание доставки"})));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Warehouse/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Warehouse.BusinessLogicLayer.Interfaces;
using Warehouse.BusinessLogicLayer.DataTransferObjects;
using AutoMapper;
using Warehouse.ViewModels;
using Warehouse.BusinessLogicLayer.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Warehouse.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        private readonly IMapper _mapper;
        private readonly IUnitService _unitService;
        private readonly ICountriesService _countriesService;

        public ProductsController(IProductService productService, IUnitService unitService, IMapper mapper, ICountriesService countriesService)
        {
            _productService = productService;
            _mapper = mapper;
            _unitService = unitService;
            _countriesService = countriesService;
        }

        public ActionResult Index(ProductFilterParams f)
        {
            if (f.MinCount == null) f.MinCount = 1;
            var products = _mapper.Map<IEnumerable<ProductViewModel>>(_productService.ReadMany(f));
            var viewModel = _mapper.Map<ProductFilterViewModel>(f);
            viewModel.Products = products;
            return View(viewModel);
        }

        public async Task<ActionResult> Details(int id)
        {
            try
            {
                ProductViewModel p = _mapper.Map<ProductViewModel>(await _productService.ReadAsync(id));
                if (p == null) Response.StatusCode = 404;
                return View(p);
            }
            catch
            {
                return NotFound();
            }
        }

        public ActionResult Create()
        {
            ViewBag.Units = new SelectList(_unitService.ReadAll(), "Id", "UnitString");
            ViewBag.Countries = new SelectList(_countriesService.ReadAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductViewModel p, IFormCollection collection)
        {
            try
            {
                p.Pictures = collection["pictures"].Select(s => new UrlViewModel { UrlString = s }).ToList();
                var id = await _productService.CreateAsync(_mapper.Map<ProductDTO>(p));
                return RedirectToAction(nameof(Details), new { Id = id });
            }
            catch
            {
                return Create();
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            var defSelect = new SelectListItem { Value = "-1", Text = "Не выбрано", Selected = true };
            ViewBag.Units = (new SelectList(_unitService.ReadAll(), "Id", "UnitString")).Append(defSelect);
            ViewBag.Countries = (new SelectList(_countriesService.ReadAll(), "Id", "Name")).Append(defSelect);
            return View(_mapper.Map<ProductViewModel>(await _productService.ReadAsync(id)));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProductViewModel p, IFormCollection collection)
        {
            try
            {
                p.Pictures = collection["pictures"].Select(s => new UrlViewModel { UrlString = s }).ToList();
                await _productService.UpdateAsync(_mapper.Map<ProductDTO>(p));

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var product = await _productService.ReadAsync(id);
                if (product == null) return NotFound();
                await _productService.DeleteAsync(product);

                return Ok();
            }
            catch
            {
                return BadRequest();
            }
        }
    }
}

Warehouse/Controllers/ShipmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Warehouse.BusinessLogicLayer.DataTransferObjects;
using Warehouse.BusinessLogicLayer.Interfaces;
using Warehouse.ViewModels;

namespace Warehouse.Controllers
{
    public class ShipmentsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IShipmentService _service;
        private readonly IDocumentService _documentService;
        public ShipmentsController(IMapper mapper, IShipmentService service, IDocumentService documentService)
        {
            _mapper = mapper;
            _service = service;
            _documentService = documentService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> DownloadDocx(int id)
        {
            try
            {
                var shipment = await _service.ReadAsync(id);
                if (shipment == null) return NotFound();
                var documentStream = _documentService.CreateWordInvoice(shipment);

                return File(documentStream,
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    $"invoice_{id}.docx");
            }
            catch
            {
                return StatusCode(500);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(ShipmentViewModel shipment)
        {
            try
            {
                await _service.CreateAsync(_mapper.Map<ShipmentDTO>(shipment));
                return Redirect($"/orders/details/{shipment.OrderId}");
            }
            catch
            {
                return BadRequest();
            }

        }
    }
}

Warehouse/Views/Orders/All.cshtml
@using ViewModels
@model IEnumerable<OrderViewModel>

@{
    ViewData["Title"] = "Все заказы";
    Layout = "_Layout";
}

@foreach (var o in Model)
{
    <p><a asp-controller="Orders" asp-action="Details" asp-route-id="@o.Id">Заказ №@o.Id. @o.OrderDate @o.TotalPrice</a></p>
}

Warehouse/Views/Orders/Create.cshtml
@using Warehouse.ViewModels
@using Warehouse.ClassLibrary
@model IEnumerable<ProductViewModel>
@{
    ViewData["Title"] = $"Заказать {Model.First().Name}";
    Layout = "_Layout";
}

<h3>Ваш заказ:</h3>

<div class="card margin-bottom-15px col-lg-9">
    <div class="card-body">
        <div>
            @foreach (var orderItem in Model)
            {
                <div class="card card-secondary lg-12">
                    <div class="row no-gutters">
                        <div class="col-lg-2">
                            <img src="@orderItem.Pictures.FirstOrDefault()" class="card-img" alt="...">
                        </div>
                        <div class="col-lg-8">
                            <div class="card-body">
                                <h6 class="card-title"><a asp-controller="Products" asp-action="Details" asp-route-id="@orderItem.Id">@orderItem.Name</a></h6>
                                <p class="card-text" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">@orderItem.Description</p>
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <h6><b>@orderItem.Price</b></h6>
                        </div>
                    </div>
                </div>

            }
        </div>
        @{ 
            Price resPrice = new Price(Model.Sum(p => p.Price.Penny));
        }
        <p>Итоговая стоимость: <b>@resPrice</b></p>
    </div>
</div>


<section class="order-form my-4 mx-4 col-lg-9">
    <div class="container pt-4">
        <form action="/orders/create" method="post">
            @foreach(var p in Model)
            {
                <input type="hidden" name="ids[]" value="@p.Id" />
            }
            <div class="row">
                <div class="col-12">
                    <h3>Данные доставки</h3>
                    <hr class="mt-1">
                </div>
                <div class="col-12">

                    <div class="row mx-4">
                        <div class="col-12 mb-2">
                            <label class="order-form-label">Имя</label>
                        </div>
                        <div class="col-12 col-sm-6">
                            <input name="name" class="order-form-input" placeholder="Иван" required>
                        </div>
                        <div class="col-12 col-sm-6 mt-2 mt-sm-0">
                            <input name="surname" class="order-form-input" placeholder="Иванов" required>
                        </div>
                    </div>

                    <div class="row mt-3 mx-4">
                        <div class="col-12">
                            <label class="order-form-label">Номер телефона</label>
                        </div>
                        <div class="col-12">
                            <input name="phoneNumber" class="order-form-input" placeholder=" " required>
                        </div>
                    </div>

                    <div class="row mt-3 mx-4">
                        <div class="col-12">
                            <label class="order-form-label">Адрес доставки</label>
                        </div>
                        <div class="col-12">
                            <input name="street" class="order-form-input" placeholder="Улица" required>
                        </div>
                        <div class="col-12 mt-2">
                            <input name="house" class="order-form-input" placeholder="Дом" required>
                        </div>
                        <div class="col-12 col-sm-6 mt-2 pr-sm-2">
                            <input name="city" class="order-form-input" placeholder="Город" required>
                        </div>
                        <div class="col-12 col-sm-6 mt-2 pr-sm-2">
                            <input name="zipCode" class="order-form-input" placeholder="Индекс" required>
                        </div>
                    </div>


                    <div class="row mt-3">
                        <div class="col-12">
                            <button type="submit" id="btnSubmit" class="btn btn-primary d-block mx-auto btn-submit">Заказать</button>
                        </div>
                    </div>

                </div>
            </div>
        </form>
    </div>
</section>

Warehouse/Views/Orders/Deliver.cshtml
@using Warehouse.ViewModels
@model IEnumerable<OrderViewModel>
@{
    ViewData["Title"] = "Оформить новый товар";
    Layout = "_Layout";
}

<h2>Ожидают доставку:</h2>
<ul class="list-group">
    @foreach (var o in Model)
    {
        <li class="list-group-item">
            <a asp-controller="Orders" asp-action="Details" asp-route-id="@o.Id">
                Заказ №@o.Id. @o.Items.Sum(o => o.Product.Weight) кг. улица пушкина, дом колотушкина
            </a>
        </li>
    }
</ul>

Warehouse/Views/Orders/Details.cshtml
@using Warehouse.ViewModels
@using Warehouse.BusinessLogicLayer.Extensions;
@model OrderViewModel

@{
    Layout = "_Layout";
}

@if (Model == null)
{
    ViewData["Title"] = "Заказ не найден";
    <h1>Заказ не найден</h1>
    return;
}


@{
    string conveyed = null;
    string recepient = null;
}

@if (Model != null)
{
    ViewData["Title"] = $"Детали заказа {Model?.Id}";
    <h3>Заказ №@Model.Id <small class="text-muted">@Model.OrderDate.ToString("HH:mm dd MMMM yyyy")</small></h3>

    <div class="card margin-bottom-15px col-lg-9">
        <div class="card-body">

            <div>
                @foreach (var orderItem in Model.Items)
                {
                    <div class="card card-secondary lg-12">
                        <div class="row no-gutters">
                            <div class="col-lg-2">
                                <img src="@orderItem.Product.Pictures.FirstOrDefault()" class="card-img" alt="...">
                            </div>
                            <div class="col-lg-8">
                                <div class="card-body">
                                    <h6 class="card-title"><a asp-controller="Products" asp-action="Details" asp-route-id="@orderItem.Product.Id">@orderItem.Product.Name</a></h6>
                                    <p class="card-text" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">@orderItem.Product.Description</p>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <h6><b>@orderItem.Price</b></h6>
                            </div>
                        </div>
                    </div>

                }
            </div>
            <p>Итоговая стоимость: <b>@Model.TotalPrice</b></p>

        </div>


        <div class="d-flex justify-content-center margin-bottom-15px">
            <div class="col-lg-9">
                <div class="card">
                    <div class="card-title">История состояний заказа:</div>
                    <table class="card-body">
                        @foreach (var os in Model?.OrderStatuses)
                        {
                            <tr>
                                <td>
                                    <p class="card-text"><small>@os.DateTime.ToString("dd.MM.yyyy HH:mm")</small></p>
                                </td>
                                <td>
                                    <p class="card-text">@os.OrderStatus</p>
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
        @if (User.Identity.Name == "StoreKeeper1@gmail.com" || User.Identity.Name == "Adm1n@gmail.com")
        {
            <div class="d-flex justify-content-center margin-bottom-15px">
                <div class="col-lg-9">
                    <div class="card">
                        <div class="card-title">История прием-передач:</div>
                        <table class="card-body">
                            <tr><th>Дата</th><th>Отдал</th><th>Получил</th></tr>
                            @foreach (var shipment in Model?.Shipments)
                            {
                                conveyed = shipment.Conveyed?.UserName ?? shipment.ConveyedName;
                                recepient = shipment.Repicient?.UserName ?? shipment.RepicientName;

                                <tr>
                                    <td>
                                        <p class="card-text"><small>@shipment.DateTime.ToString("dd.MM.yyyy HH:mm")</small></p>
                                    </td>
                                    <td>
                                        <p class="card-text">@conveyed</p>
                                    </td>
                                    <td>
                                        <p class="card-text">@recepient</p>
                                    </td>
                                    <td>
                                        <a asp-controller="Shipments" asp-action="DownloadDocx" asp-route-id="@shipment.Id">
                                            <i class="far fa-file-word" aria-hidden="true"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
            </div>

            @if (Model?.OrderStatuses?.First().OrderStatus.OrderStatusString == "Ожидание доставки")
            {
                <form method="post" action="/shipments/create">
                    <input name="OrderId" value="@Model.Id" hidden />
                    <input name="ConveyedApplicationUserId" value="@User.GetUserId()" hidden />
                    <div class="row">
                        <div class="col">
                            @Html.DropDownList("RepicientApplicationUserId", ViewBag.Couriers as SelectList, new { @class = "form-control" })
                        </div>
                        <div class="col">
                            <button type="submit" class="btn btn-primary">Отдать курьеру</button>
                        </div>
                    </div>
                </form>
                <form method="post" action="/shipments/create">
                    <input name="OrderId" value="@Model.Id" hidden />
                    <input name="OrderId" value="@Model.Id" hidden />
                    <div class="row">
                        <div class="col-12">
                            <h3>Добавить прием-передачу</h3>
                            <hr class="mt-1">
                        </div>
                        <div class="col-12">

                            <div class="row mx-4">
                                <div class="col-12 mb-2">
                                    <label class="order-form-label">ФИО Отдающий</label>
                                </div>
                                <div class="col-12 col-sm-12">
                                    <input name="СonveyedName" class="order-form-input" placeholder="Иванов Иван Иванович" required>
                                </div>
                            </div>

                            <div class="row mt-3 mx-4">
                                <div class="col-12">
                                    <label class="order-form-label">ФИО Получатель</label>
                                </div>
                                <div class="col-12">
                                    <input name="RepicientName" class="order-form-input" placeholder="Иванов Иван Иванович" required>
                                </div>
                            </div>

                            <div class="row mt-3">
                                <div class="col-12">
                                    <button type="submit" id="btnSubmit" class="btn btn-primary d-block mx-auto btn-submit">Добавить</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </form>
            }
        }
        @if (User.Identity.Name == "Accountant1@gmail.com" || User.Identity.Name == "Adm1n@gmail.com")
        {

            @if (Model?.OrderStatuses?.First().OrderStatus.OrderStatusString == "Ожидание оплаты")
            {
                <form method="post" action="/orders/setPayed">
                    <input name="id" value="@Model.Id" hidden />
                    <button type="submit" class="btn btn-primary btn-md active">Оплачен</button>
                </form>
            }
        }
        @if (User.GetUserId() == Model.Shipments.FirstOrDefault()?.RepicientApplicationUserId
           && Model?.OrderStatuses?.First().OrderStatus.OrderStatusString == "Передан курьеру")
        {
            <form method="post" action="/shipments/create">
                <input name="OrderId" value="@Model.Id" hidden />
                <input name="ConveyedApplicationUserId" value="@User.GetUserId()" hidden />
                <input name="RepicientApplicationUserId" value="@Model.UserId" hidden />
                <button type="submit" class="btn btn-primary">Передан клиенту</button>
            </form>
        }
    </div>
}
else
{
    <h1>Заказ не найден</h1>
    ViewData["Title"] = "Заказ не найден";
}

Warehouse/Views/Orders/Index.cshtml
@using Warehouse.ViewModels
@model IEnumerable<OrderViewModel>
@{
    ViewData["Title"] = "Мои заказы";
    Layout = "_Layout";
}

@foreach (var o in Model)
{
    <div class="card margin-bottom-15px">
        <a asp-action="Details" asp-route-id="@o.Id" class="card-title" style="margin-left:30px;">Заказ №@o.Id <small class="text-muted">@o.OrderDate.ToString("HH:mm dd MMMM yyyy")</small></a>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-8">
                    @foreach (var orderItem in o.Items)
                    {
                        <div class="card card-secondary lg-12">
                            <div class="row no-gutters">
                                <div class="col-lg-2">
                                    <img src="@orderItem.Product.Pictures.FirstOrDefault()" class="card-img" alt="...">
                                </div>
                                <div class="col-lg-8">
                                    <div class="card-body">
                                        <h6 class="card-title"><a asp-controller="Products" asp-action="Details" asp-route-id="@orderItem.Product.Id">@orderItem.Product.Name</a></h6>
                                        <p class="card-text" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">@orderItem.Product.Description</p>
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <h6><b>@orderItem.Price</b></h6>
                                </div>
                            </div>
                        </div>

                    }
                </div>
                <div class="col-auto">
                    <p>Итоговая стоимость: <b>@o.TotalPrice</b></p>
                    <div class="card">
                        <div class="text-center">
                            <div class="card-title">Состояние заказа:</div>
                            <p class="card-text">@o.OrderStatuses?.FirstOrDefault()?.OrderStatus?.OrderStatusString</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Warehouse/Views/Orders/Unpaid.cshtml
@using ViewModels
@model IEnumerable<OrderViewModel>

@{
    ViewData["Title"] = "Неоплаченные заказы";
    Layout = "_Layout";
}

@foreach (var o in Model)
{
    <p><a asp-controller="Orders" asp-action="Details" asp-route-id="@o.Id">Заказ №@o.Id. @o.OrderDate @o.TotalPrice</a></p>
}